### PR TITLE
Replace swagger to drf_yasg

### PR DESCRIPTION
**Pull request by NeOneSoft**
### Description
This PR was created on behalf of [PR](https://github.com/openedx/django-user-tasks/pull/176) to solve some conflicts regarding python 3.8 dependencies.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @NeOneSoft!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by NeOneSoft** [comment]
Hi @natabene!! I created this PR to solve the python 3.8 dependencies conflicts since I had been experiencing similar issues in another repositories so I would like to ask for the last review here and once it's merged we could closed the original. Thank you so much for your support!!

**Comment by natabene** [comment]
@NeOneSoft Thank you for your contribution!

**Comment by timmc-edx** [comment]
Looks like this one is missing the dependency change from https://github.com/openedx/django-user-tasks/pull/176. Would it make more sense to go back to the original PR, remove the .txt requirements changes, rebase, and then re-compile requirements?

**Comment by NeOneSoft** [comment]
Hi @timmc-edx, thank you so much for your support!!. What you suggest makes sense for me!! I only continue using this PR to test if the changes on the dependencies works since it was a little bit confusing for me

**Review by timmc-edx — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@NeOneSoft 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/django-user-tasks&entry.867055334=https://github.com/openedx/django-user-tasks/pull/226&entry.1484655318=https://github.com/NeOneSoft&entry.752974735=2022-07-22+17:52&entry.1917517419=2022-08-03+18:59&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
