### PR TITLE
feat!: bump celery and drop python 3.5

### PR DESCRIPTION
**Pull request by gabor-boros**
## Description

This PR removes Celery<5 pin from requirements, so resolves a dependency conflict in https://github.com/openedx/edx-platform/pull/29046.

## Supporting information

For more information, please see the linked PR.

### CODE REVIEW

**Comment by edx-webhook** [comment]
Thanks for the pull request, @gabor-boros! I've created [OSPR-6443](https://openedx.atlassian.net/browse/OSPR-6443) to keep track of it in JIRA, where we prioritize reviews. Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by awais786 — APPROVED** [review]

**Review by awais786 — APPROVED** [review]

**Comment by gabor-boros** [comment]
@awais786 Thank you for the review! Please not that it would require a release as well to profit get unblocked on Celery side.

**Comment by edx-webhook** [comment]
@gabor-boros 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/django-user-tasks&entry.867055334=https://github.com/openedx/django-user-tasks/pull/199&entry.1484655318=https://github.com/gabor-boros&entry.752974735=2022-02-08+12:01&entry.1917517419=2022-02-09+10:26&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by iamsobanjaved** [comment]
@gabor-boros I have merged this PR and also released the new version.

**Comment by natabene** [comment]
@gabor-boros Thank you for your contribution. @iamsobanjaved Thanks for reviewing and merging!

**Pull request merged**
