### PR TITLE
Replace rest_framework_swagger with drf_yasg

### PR DESCRIPTION
**Pull request by NeOneSoft**
This PR was created following edx/upgrades#17 to switch django rest swagger to drf-yasg

### CODE REVIEW

**Comment by NeOneSoft** [comment]
Hey there @NeOneSoft !!.I already fix the conflicts. Could you please review this PR.?Thank you so much

**Comment by awais786** [comment]
I have verified its working. Please rebase.

Screen Shot 2022-01-24 at 12 57 35 PM

**Review by awais786 — APPROVED** [review]

**Comment by UsamaSadiq** [comment]
@NeOneSoft The PR is ready to merge now. Could you rebase and resolve the conflicts once so I'll go ahead and merge this PR. 
Thanks.

**Comment by NeOneSoft** [comment]
Hi @UsamaSadiq !! I already rebased, resolved the conflicts and squash  the commits to clean up the PR, now is ready to check it if you are aggree. Thanks in advance !!

**Comment by UsamaSadiq** [comment]
Hi @NeOneSoft thanks for the effort. Seems like the quality failure will also need to be fixed before the PR can be merged. Could you have a look at the failures once you get opportunity. Thanks.

**Comment by natabene** [comment]
@NeOneSoft Did you have a chance to implement the feedback?

**Comment by NeOneSoft** [comment]
Hi@natabene, yes I already modified according the feedback but it seems that I'm having an import issue. I will check it and let you know once it's done. Thanks

**Comment by natabene** [comment]
@NeOneSoft Just checking if you had a chance to look into this.

**Comment by NeOneSoft** [comment]
Hi @natabene, sorry for my delay to answer. I will working on it tomorrow and let you know once is ready

**Comment by timmc-edx** [comment]
Addressed in https://github.com/openedx/django-user-tasks/pull/226

**Comment by openedx-webhooks** [comment]
@NeOneSoft Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/django-user-tasks&entry.867055334=https://github.com/openedx/django-user-tasks/pull/176&entry.1484655318=https://github.com/NeOneSoft&entry.752974735=2021-10-12+16:44&entry.1917517419=2022-08-03+19:01&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
